# site properties and page defaults
title: Digital Twin & Robot Ecosystems with AI for Mobility, Manufacturing, and Management (DREAM3) Lab.
subtitle: CCE, University of Florida
description: Test

url: "https://dream3lab.github.io"   
baseurl: ""                             

header-dark: false

# site social media and other links
links:
  email: shuai.li@essie.ufl.edu
  #orcid: 0000-0001-8713-9213
  google-scholar: xeoJ8Y8AAAAJ
  # github: https://github.com/AIS-SNU
  #twitter: AIS-SNU
  #youtube: AIS-SNU

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "alumni"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
